name: CI (minimal)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # flake8 is listed in requirements; if not, uncomment next line:
          # pip install flake8

      - name: Lint (honor .flake8 config)
        run: flake8 .

      - name: Run placeholder test only
        run: pytest -q tests/test_placeholder.py -vv
